site_name: Docs for hj3415
theme:
  name: material
  features:
    - navigation.sections     # 섹션을 시각적으로 구분(들여쓰기 스타일)
    #- navigation.expand       # 모든 섹션 기본 펼침
    - navigation.indexes      # 폴더도 문서처럼 다루기
    #- navigation.top          # 스크롤 시 상단 이동 버튼
    - navigation.instant     # 페이지 새로고침 없이 SPA처럼 빠르게 이동
    - search.suggest          # 검색 자동완성
    - search.highlight    # 검색어가 본문에 하이라이트
    - content.code.copy      # 코드 블록에 복사 버튼 자동 추가
    - header.autohide       # 스크롤 시 상단 헤더 자동 숨김
    #- toc.integrate         # 페이지 좌측이 아닌 콘텐츠 상단에 소목차 표시
    - content.action.edit
    - content.action.view

repo_url: https://github.com/hj3415/hj3415.github.io
edit_uri: edit/main/docs/

plugins:
  - search
  - obsidian-support

markdown_extensions:
  - admonition         # ›> "!!! note", "!!! warning" 등 사용 가능
  - attr_list          # 이미지/텍스트에 { width="50%" } 등 스타일 지정
  - pymdownx.details   # 접는 블록 (??? note "제목")
  - pymdownx.superfences   # fenced code 블록 중첩 지원
  - pymdownx.highlight     # 코드 하이라이트 옵션 강화