site_name: Docs for hj3415
theme:
  name: material
  features:
    - navigation.sections     # 섹션 전체 펼치기
    - navigation.expand       # 현재 위치 기반 자동 확장
    - navigation.indexes      # 폴더도 문서처럼 다루기
nav:
  - Home: index.md
  - GDQUEST:
    - 2D:
      - M9 Top Down Movement:
        - L1 Top Down Movement - Module Overview: GDQUEST/2D/M9_Top_Down_Movement/L1_Top_Down_Movement_Module_Overview/L1_Top_Down_Movement_Module_Overview.md
    - 용어정의:
      - 9-slice scaling: GDQUEST/Glossary/9-slice_scaling/9-slice_scaling.md
      - AI (Game AI): GDQUEST/Glossary/AI_(Game_AI)/AI_(Game_AI).md
      - Game Jam: GDQUEST/Glossary/Game_Jam/Game_Jam.md
plugins:
  - obsidian-support
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences